const fs = require('fs');
const path = require('path');

const itemsData = [
  {
    num: 1,
    ar: "آلة استخراج العسل",
    en: "Honey Extractor",
    zh: "蜂蜜提取机",
    desc_ar: "عصارة عسل يدوية من الفولاذ المقاوم للصدأ، تتسع لأربعة أطر، تعمل بقوة الطرد المركزي. طريقة الاستخدام: توضع أقراص العسل المفرغة في السلة الدوارة، ويتم تدوير المقبض اليدوي، فتطير قطرات العسل وتلتصق بجدران الحوض، ثم تصب من الصنبور السفلي.",
    short_ar: "عصارة عسل يدوية من الفولاذ المقاوم للصدأ تتسع لأربعة أطر.",
    category: "Agricultural machinery",
    price: 1850.00
  },
  {
    num: 2,
    ar: "مطحنة مطرقية",
    en: "Hammer Mill",
    zh: "锤式粉碎机",
    desc_ar: "آلة طحن قوية تعتمد على مضارب معدنية دوارة، تستخدم لسحق الحبوب والمواد الجافة بسرعة عالية. طريقة الاستخدام: توضع المواد الخام في القادوس العلوي، وتقوم الشفرات الدوارة بسحقها إلى مسحوق ناعم يخرج من فتحة التفريغ السفلية.",
    short_ar: "آلة طحن قوية تعتمد على مضارب معدنية دوارة لسحق الحبوب.",
    category: "Gain machinery",
    price: 3400.00
  },
  {
    num: 3,
    ar: "آلة تقشير الفول السوداني",
    en: "Peanut Shelling Machine",
    zh: "花生剥壳机",
    desc_ar: "آلة متخصصة لنزع القشرة الخارجية عن حبات الفول السوداني الجاف دون إتلاف اللب. طريقة الاستخدام: يُصب الفول السوداني الجاف في القادوس، وتقوم آلية الدرس اللطيفة بفصل القشر عن اللب، حيث يخرج القشر من فتحة علوية، وتخرج الحبات من فتحة سفلية.",
    short_ar: "آلة متخصصة لنزع القشرة الخارجية عن حبات الفول السوداني.",
    category: "Agricultural machinery",
    price: 2200.00
  },
  {
    num: 4,
    ar: "آلة الأعلاف المتكاملة",
    en: "Integrated Feed Machine",
    zh: "多功能饲料机",
    desc_ar: "آلة زراعية متعددة الوظائف لتقطيع القش والأعشاب وطحن الحبوب لتحضير أعلاف الماشية والدواجن. طريقة الاستخدام: توضع الأعلاف الخام في القادوس العلوي، وتقوم الشفرات الدوارة بتقطيعها وطحنها، ويخرج العلف النهائي من الفتحات السفلية للتجميع.",
    short_ar: "آلة زراعية متعددة الوظائف لتقطيع القش وطحن الحبوب.",
    category: "Agricultural machinery",
    price: 4100.00
  },
  {
    num: 5,
    ar: "مطحنة حبوب كهربائية",
    en: "Electric Grain Mill",
    zh: "电动磨粉机",
    desc_ar: "مطحنة كهربائية مدمجة للمنازل والمزارع الصغيرة، لطحن الحبوب والبهارات إلى درجات نعومة مختلفة. طريقة الاستخدام: توضع الحبوب في القادوس، ويتم تشغيل المحرك. يمكن تعديل خشونة الطحن باستخدام براغي الضبط، ويخرج الدقيق من الفوهة الأمامية.",
    short_ar: "مطحنة كهربائية مدمجة للمنازل والمزارع الصغيرة لطحن الحبوب.",
    category: "Gain machinery",
    price: 1250.00
  },
  {
    num: 6,
    ar: "آلة كريات الأعلاف",
    en: "Feed Pellet Machine",
    zh: "饲料制粒机",
    desc_ar: "مكبس لتشكيل مسحوق العلف إلى كريات (بيليه) صلبة لتغذية الدواجن والمواشي، مما يسهل التخزين ويقلل الهدر. طريقة الاستخدام: يُخلط مسحوق العلف مع الماء، ويوضع في القادوس، ثم تقوم البكرات الدوارة بضغطه من خلال القوالب لتشكيل الكريات الصلبة.",
    short_ar: "مكبس لتشكيل مسحوق العلف إلى كريات صلبة لتغذية الدواجن.",
    category: "Agricultural machinery",
    price: 3800.00
  },
  {
    num: 7,
    ar: "آلة استخراج العسل (4 أطر)",
    en: "Honey Extractor (4 Frames)",
    zh: "蜂蜜提取机 (四框)",
    desc_ar: "عصارة عسل يدوية مثبتة على أربع أرجل ثابتة، تتسع لأربعة أطر، مصممة للهواة ومربي النحل. طريقة الاستخدام: توضع الأطر في الحامل الدوار، وتدور الآلية يدوياً، ويتم جمع العسل المتطاير من الصنبور السفلي.",
    short_ar: "عصارة عسل يدوية مثبتة على 4 أرجل ثابتة تتسع 4 أطر.",
    category: "Agricultural machinery",
    price: 1950.00
  },
  {
    num: 8,
    ar: "نول نسيج الأشرطة",
    en: "Ribbon Weaving Loom",
    zh: "织带机",
    desc_ar: "آلة نسيج صناعية متخصصة في نسج السيور والأشرطة الضيقة باستخدام إبر ميكانيكية. طريقة الاستخدام: يتم تغذية الخيوط من البكرات الخلفية، وتقوم الإبر الدوارة بنسجها لتشكيل شريط مستمر يخرج من مقدمة الآلة.",
    short_ar: "آلة نسيج صناعية متخصصة في نسج السيور والأشرطة الضيقة.",
    category: "Textile Machinery",
    price: 6500.00
  },
  {
    num: 9,
    ar: "واجهة مبنى هندسية",
    en: "Geometric Building Facade",
    zh: "几何建筑外墙",
    desc_ar: "نظام واجهات معمارية حديثة مصنوع من ألواح معدنية مثلثية ثلاثية الأبعاد مع إضاءة LED مدمجة. طريقة الاستخدام: يتم تركيب الألواح المعدنية على هيكل المبنى، وتعمل الإضاءة المدمجة على خلق تأثيرات بصرية ليلية مذهلة.",
    short_ar: "نظام واجهات معمارية حديثة من ألواح معدنية مثلثية 3D.",
    category: "Metal products",
    price: 8900.00
  },
  {
    num: 10,
    ar: "لفائف معدنية ملونة",
    en: "Colored Metal Coils",
    zh: "彩色金属卷材",
    desc_ar: "لفائف فولاذية وألمنيوم مطلية مسبقاً بألوان متعددة ومقاومة للصدأ، تستخدم في الأسقف والجدران. طريقة الاستخدام: يتم فك اللفائف وتقطيعها إلى صفائح، ثم تركيبها باستخدام البراغي على الأسطح المطلوبة.",
    short_ar: "لفائف فولاذية وألمنيوم مطلية مسبقاً بألوان متعددة.",
    category: "Metal products",
    price: 5200.00
  },
  {
    num: 11,
    ar: "بلاط سيراميك مزخرف",
    en: "Decorative Ceramic Tile",
    zh: "装饰陶瓷砖",
    desc_ar: "بلاط سيراميك مصقول بتصميم هندسي للمربعات وزخرفة نباتية في المركز، يضيف لمسة فخامة للديكور. طريقة الاستخدام: يتم تركيب البلاط باستخدام الأسمنت والرمل، ويمكن استخدامه للأرضيات والجدران في الحمامات والمطابخ.",
    short_ar: "بلاط سيراميك مصقول بتصميم هندسي وزخرفة نباتية.",
    category: "Products",
    price: 85.00
  },
  {
    num: 12,
    ar: "لوح معدني مموج",
    en: "Corrugated Metal Sheet",
    zh: "波纹金属板",
    desc_ar: "لوح صاج مضلع مطلي باللون البرتقالي، يستخدم لتسقيف وتكسية جدران المباني الصناعية والزراعية. طريقة الاستخدام: يتم قص الألواح للطول المطلوب، وتثبيتها على الهيكل الحديدي باستخدام مسامير خاصة منعاً لتسرب المياه.",
    short_ar: "لوح صاج مضلع مطلي لتسقيف وتكسية الجدران الصناعية.",
    category: "Metal products",
    price: 120.00
  },
  {
    num: 13,
    ar: "لفائف صاج الطوب",
    en: "Brick Pattern Coil",
    zh: "砖纹金属卷材",
    desc_ar: "لفة معدنية مطلية بنقش طوب ثلاثي الأبعاد، تستخدم ككسوة خارجية للمباني الحديثة والمنازل الجاهزة. طريقة الاستخدام: يتم فك اللفائف وتقطيعها إلى ألواح، ثم تثبيتها على واجهات المباني لإعطاء مظهر الطوب التقليدي.",
    short_ar: "لفة معدنية مطلية بنقش طوب 3D ككسوة خارجية للمباني.",
    category: "Metal products",
    price: 4800.00
  },
  {
    num: 14,
    ar: "سير مضلع",
    en: "Ribbed Belt",
    zh: "多楔带",
    desc_ar: "سير مطاطي مضلع لنقل الحركة في السيارات والمحركات، يمنع الانزلاق ويضمن تشغيلاً هادئاً. طريقة الاستخدام: يتم تركيب السير على البكرات الدوارة، ويقوم بنقل الحركة من المحرك إلى الملحقات كالدينامو والمكيف.",
    short_ar: "سير مطاطي مضلع لنقل الحركة في السيارات والمحركات.",
    category: "Car spare parts",
    price: 45.00
  },
  {
    num: 15,
    ar: "فلتر زيت ACDelco",
    en: "ACDelco Oil Filter",
    zh: "ACDelco机油滤清器",
    desc_ar: "فلتر زيت محرك عالي الأداء يحبس الشوائب الدقيقة للحفاظ على نظافة زيت المحرك. طريقة الاستخدام: يتم فك الفلتر القديم وتركيب الفلتر الجديد على واجهة المحرك، وربطه بإحكام، ثم يُملأ المحرك بالزيت الجديد.",
    short_ar: "فلتر زيت محرك عالي الأداء يحبس الشوائب الدقيقة.",
    category: "Car spare parts",
    price: 25.00
  },
  {
    num: 16,
    ar: "آلة CNC متعددة الرؤوس",
    en: "Multi-head CNC Router",
    zh: "多头数控雕刻机",
    desc_ar: "آلة CNC بأربعة رؤوس دوارة متزامنة لقطع وحفر الأخشاب بكميات كبيرة. طريقة الاستخدام: يتم تحميل تصميم القطع على الكمبيوتر، وتثبيت لوح الخشب على الطاولة، وتقوم الآلة بالقطع والنحت تلقائياً.",
    short_ar: "آلة CNC بأربعة رؤوس دوارة متزامنة لقطع وحفر الأخشاب.",
    category: "CNC machinery",
    price: 14500.00
  },
  {
    num: 17,
    ar: "آلة CNC ليزر/بلازما",
    en: "CNC Laser/Plasma Cutter",
    zh: "数控激光/等离子切割机",
    desc_ar: "آلة CNC برأس واحد قابلة للتبديل، تدعم تقنيات القطع بالليزر والبلازما بدقة عالية. طريقة الاستخدام: يتم اختيار رأس القطع المناسب، وتثبيت المادة على الطاولة، وتعمل الآلة على قص التصميمات المعقدة تلقائياً.",
    short_ar: "آلة CNC تدعم تقنيات القطع بالليزر والبلازما بدقة عالية.",
    category: "Laser & Cutting",
    price: 18900.00
  },
  {
    num: 18,
    ar: "آلة CNC مسطحة",
    en: "Flatbed CNC Router",
    zh: "平板数控雕刻机",
    desc_ar: "آلة CNC مسطحة مع نظام تحكم مدمج، مثالية لورش النجارة الصغيرة والمتوسطة. طريقة الاستخدام: توضع المادة الخام على الطاولة المسطحة، ويتم تشغيل الآلة من لوحة التحكم لقص ونحت الأخشاب بدقة.",
    short_ar: "آلة CNC مسطحة مع نظام تحكم مدمج لورش النجارة.",
    category: "CNC machinery",
    price: 11200.00
  },
  {
    num: 19,
    ar: "آلة قطع بالليزر",
    en: "Laser Cutting Machine",
    zh: "激光切割机",
    desc_ar: "آلة صناعية لقطع الصفائح المعدنية والأكريليك باستخدام شعاع ليزر عالي الطاقة. طريقة الاستخدام: يتم وضع الصفيحة على الطاولة، وبرمجة التصميم، وتقوم الآلة بقص المادة بدقة متناهية دون لمسها ميكانيكياً.",
    short_ar: "آلة صناعية لقطع الصفائح المعدنية والأكريليك بالليزر.",
    category: "Laser & Cutting",
    price: 24500.00
  },
  {
    num: 20,
    ar: "آلة طحن حجرية دوارة",
    en: "Rotary Stone Mill",
    zh: "旋转石磨机",
    desc_ar: "مطحنة حجرية تقليدية بحجرين دوارين لطحن الحبوب، توفر طحناً بارداً يحافظ على النكهة. طريقة الاستخدام: توضع الحبوب بين الحجرين الدوارين، وعند دوران المحرك، تطحن الحبوب ببطء دون توليد حرارة عالية.",
    short_ar: "مطحنة حجرية تقليدية بحجرين دوارين لطحن الحبوب.",
    category: "Gain machinery",
    price: 2800.00
  },
  { num: 21, ar: "آلة طحن صناعية ثقيلة", en: "Heavy-duty Industrial Mill", zh: "重型工业研磨机", category: "Gain machinery", price: 7800.00 },
  { num: 22, ar: "آلة تنظيف القطن", en: "Cotton Cleaning Machine", zh: "棉花清理机", category: "Cotton picker", price: 5400.00 },
  { num: 23, ar: "مروحة محمولة قابلة للشحن", en: "Portable Rechargeable Fan", zh: "便携式充电风扇", category: "Electric appliance", price: 45.00 },
  { num: 24, ar: "مروحة محمولة (مواصفات)", en: "Portable Fan (Specs)", zh: "便携式风扇 (规格)", category: "Electric appliance", price: 50.00 },
  { num: 25, ar: "مروحة خارجية محمولة", en: "Portable Outdoor Fan", zh: "便携式户外风扇", category: "Electric appliance", price: 65.00 },
  { num: 26, ar: "مروحة عمودية كهربائية", en: "Electric Pedestal Fan", zh: "电动落地扇", category: "Electric appliance", price: 85.00 },
  { num: 27, ar: "مروحة شمسية قابلة للشحن", en: "Solar Rechargeable Fan", zh: "太阳能充电风扇", category: "Electric appliance", price: 110.00 },
  { num: 28, ar: "مرتبة طبية معبأة", en: "Packaged Medical Mattress", zh: "包装好的医用床垫", category: "Products", price: 320.00 },
  { num: 29, ar: "عربة نقل البراميل", en: "Drum Handling Trolley", zh: "油桶搬运车", category: "Conveyors & Logistics", price: 290.00 },
  { num: 30, ar: "قسم داخلي متحرك", en: "Movable Partition", zh: "移动隔断", category: "Products", price: 850.00 },
  { num: 31, ar: "باب زجاجي متعدد الألواح", en: "Multi-panel Glass Door", zh: "多扇玻璃门", category: "Products", price: 1450.00 },
  { num: 32, ar: "باب داخلي أبيض قابل للطي", en: "White Folding Interior Door", zh: "白色折叠室内门", category: "Products", price: 420.00 },
  { num: 33, ar: "لوح شبك سلكي", en: "Wire Mesh Panel", zh: "铁丝网板", category: "Metal products", price: 95.00 },
  { num: 34, ar: "سن دلو الحفار", en: "Excavator Bucket Tooth", zh: "挖掘机斗齿", category: "Earth moving", price: 180.00 },
  { num: 35, ar: "محرك هيدروليكي دوار", en: "Hydraulic Swing Motor", zh: "液压回转马达", category: "Earth moving", price: 3200.00 },
  { num: 36, ar: "سكين الجرافة", en: "Grader Blade", zh: "平地机刀片", category: "Earth moving", price: 680.00 },
  { num: 37, ar: "سن تمزيق ثقيل", en: "Heavy-Duty Ripper Tooth", zh: "重型裂土齿", category: "Earth moving", price: 310.00 },
  { num: 38, ar: "أجزاء عجلة دفع مسننة", en: "Sprocket Segments", zh: "链轮节", category: "Heavy Machinery Parts", price: 240.00 },
  { num: 39, ar: "شفرة قطع مسطحة مع فتحات", en: "Flat Cutting Blade", zh: "扁平切割刀片", category: "Heavy Machinery Parts", price: 150.00 },
  { num: 40, ar: "مجموعة قطع غيار معدات ثقيلة", en: "Heavy Equipment Spare Parts", zh: "重型设备备件", category: "Heavy Machinery Parts", price: 1250.00 },
  { num: 41, ar: "ألواح حماية معدنية", en: "Wear Plates", zh: "耐磨板", category: "Heavy Machinery Parts", price: 420.00 },
  { num: 42, ar: "مكبس استخلاص الزيت الهيدروليكي", en: "Hydraulic Oil Press", zh: "液压榨油机", category: "Oil press", price: 4900.00 },
  { num: 43, ar: "آلة فك تكتل الألياف", en: "Fiber Opening Machine", zh: "纤维开松机", category: "Textile Machinery", price: 3800.00 },
  { num: 44, ar: "آلة تمزيق الألياف", en: "Fiber Shredding Machine", zh: "纤维撕碎机", category: "Textile Machinery", price: 4200.00 },
  { num: 45, ar: "آلة تغذية القطن الهوائية", en: "Pneumatic Cotton Feeder", zh: "气动棉喂料机", category: "Textile Machinery", price: 3100.00 },
  { num: 46, ar: "آلة تمشيط القطن", en: "Cotton Carding Machine", zh: "梳棉机", category: "Textile Machinery", price: 7800.00 },
  { num: 47, ar: "جهاز طرد مركزي صناعي", en: "Industrial Centrifuge", zh: "工业离心机", category: "Industrial machinery", price: 8500.00 },
  { num: 48, ar: "مكبس زيت هيدروليكي عمودي", en: "Vertical Hydraulic Oil Press", zh: "立式液压榨油机", category: "Oil press", price: 5300.00 },
  { num: 49, ar: "آلة استخلاص زيت هجينة", en: "Hybrid Oil Press", zh: "混合榨油机", category: "Oil press", price: 6100.00 },
  { num: 50, ar: "آلة طباعة فلكسو (4 ألوان)", en: "Flexographic Printer (4 Colors)", zh: "柔版印刷机 (4色)", category: "Industrial machinery", price: 16500.00 },
  { num: 51, ar: "خط بثق الأفلام البلاستيكية", en: "Plastic Film Extrusion Line", zh: "塑料薄膜挤出生产线", category: "Plastic Machinery", price: 24000.00 },
  { num: 52, ar: "آلة نفخ الأفلام البلاستيكية", en: "Blown Film Machine", zh: "吹膜机", category: "Plastic Machinery", price: 18500.00 },
  { num: 53, ar: "خط إنتاج خيوط البلاستيك", en: "Plastic Yarn Production Line", zh: "塑料纱线生产线", category: "Plastic Machinery", price: 22000.00 },
  { num: 54, ar: "آلة نسيج دائرية", en: "Circular Loom", zh: "圆织机", category: "Textile Machinery", price: 12500.00 },
  { num: 55, ar: "آلة تصنيع الأكياس البلاستيكية", en: "Plastic Bag Making Machine", zh: "制袋机", category: "Plastic Machinery", price: 9800.00 },
  { num: 56, ar: "آلة نفخ الأفلام المدمجة", en: "Compact Blown Film Machine", zh: "紧凑型吹膜机", category: "Plastic Machinery", price: 14200.00 },
  { num: 57, ar: "خلاطة خرسانة ذاتية التغذية", en: "Self-Loading Concrete Mixer", zh: "自装式混凝土搅拌机", category: "Industrial machinery", price: 28500.00 },
  { num: 58, ar: "خط إنتاج الطوب الأسمنتي", en: "Concrete Block Production Line", zh: "混凝土砌块生产线", category: "Industrial machinery", price: 32000.00 },
  { num: 59, ar: "آلة غربلة الرمل", en: "Sand Screening Machine", zh: "筛沙机", category: "Mining Equipment", price: 6400.00 },
  { num: 60, ar: "خط إنتاج طوب متكامل", en: "Integrated Brick Production Line", zh: "一体化制砖生产线", category: "Industrial machinery", price: 38000.00 },
  { num: 61, ar: "خط إنتاج بلوك خرساني آلي", en: "Automatic Block Making Line", zh: "自动砌块生产线", category: "Industrial machinery", price: 42000.00 },
  { num: 62, ar: "آلة نسيج دائرية هرمية", en: "A-Frame Circular Loom", zh: "A型圆织机", category: "Textile Machinery", price: 13800.00 },
  { num: 63, ar: "هيكل معدني لمستودع", en: "Steel Warehouse Structure", zh: "钢结构仓库", category: "Metal products", price: 29000.00 },
  { num: 64, ar: "آلة غسيل الرمل الحلزونية", en: "Screw Sand Washer", zh: "螺旋洗砂机", category: "Mining Equipment", price: 8900.00 },
  { num: 65, ar: "ذراع تثبيت ميكانيكية", en: "Mechanical Tapping Arm", zh: "机械攻丝臂", category: "Industrial machinery", price: 2400.00 },
  { num: 66, ar: "روبوت تكديس الأكياس", en: "Palletizing Robot", zh: "码垛机器人", category: "Industrial Robotics", price: 26500.00 },
  { num: 67, ar: "آلة طلاء وتشطيب الورق", en: "Paper Coating Machine", zh: "纸张涂布机", category: "Industrial machinery", price: 19500.00 },
  { num: 68, ar: "آلة تشكيل طوب محمولة", en: "Portable Brick Forming Machine", zh: "便携式制砖成型机", category: "Industrial machinery", price: 4800.00 },
  { num: 69, ar: "نول نسيج مسطح صناعي", en: "Industrial Flat Loom", zh: "工业平织机", category: "Textile Machinery", price: 11000.00 },
  { num: 70, ar: "آلة قطع بالضغط الهيدروليكي", en: "Hydraulic Die Cutter", zh: "液压裁断机", category: "Heavy Presses", price: 8200.00 },
  { num: 71, ar: "آلة تقطيع الأكياس المتطورة", en: "Advanced Bag Cutting Machine", zh: "先进制袋机", category: "Plastic Machinery", price: 10500.00 },
  { num: 72, ar: "آلة لف الخيوط", en: "Yarn Winding Machine", zh: "络纱机", category: "Textile Machinery", price: 5600.00 },
  { num: 73, ar: "آلة طحن وخلط بلاستيك", en: "Plastic Mixing & Grinding Machine", zh: "塑料混合研磨机", category: "Plastic Machinery", price: 7400.00 },
  { num: 74, ar: "آلة تقطيع الأكياس متعددة الأشكال", en: "Multi-Shape Bag Cutting Machine", zh: "多形状制袋机", category: "Plastic Machinery", price: 11800.00 },
  { num: 75, ar: "كسارة بلاستيك", en: "Plastic Crusher", zh: "塑料破碎机", category: "Plastic Machinery", price: 4900.00 },
  { num: 76, ar: "خط إنتاج خيوط البلاستيك", en: "Plastic Yarn Extrusion Line", zh: "塑料纱线挤出生产线", category: "Plastic Machinery", price: 23000.00 },
  { num: 77, ar: "خط إنتاج بثق وطباعة", en: "Extrusion & Printing Line", zh: "挤出印刷生产线", category: "Plastic Machinery", price: 28000.00 },
  { num: 78, ar: "مكبس هيدروليكي للنفايات", en: "Hydraulic Baler", zh: "液压打包机", category: "Heavy Presses", price: 9200.00 },
  { num: 79, ar: "آلة تقطيع أفلام بلاستيكية", en: "Plastic Film Cutting Machine", zh: "塑料薄膜切割机", category: "Plastic Machinery", price: 6800.00 },
  { num: 80, ar: "آلة إنتاج لفائف الأكياس", en: "Roll Bag Production Machine", zh: "卷袋生产机", category: "Plastic Machinery", price: 12400.00 },
  { num: 81, ar: "نظام قطع يدوي", en: "Manual Cutting System", zh: "手动切割系统", category: "One-man tools", price: 380.00 },
  { num: 82, ar: "خط إنتاج صفائح بلاستيكية", en: "Plastic Sheet Production Line", zh: "塑料板材生产线", category: "Plastic Machinery", price: 31000.00 },
  { num: 83, ar: "آلة خياطة صناعية", en: "Industrial Sewing Machine", zh: "工业缝纫机", category: "Textile Machinery", price: 1450.00 },
  { num: 84, ar: "آلة تشكيل الصفائح المعدنية", en: "Metal Forming Machine", zh: "金属成型机", category: "Forging machinery", price: 17500.00 },
  { num: 85, ar: "آلة لف وتقطيع المرنة", en: "Slitter Rewinder Machine", zh: "分切复卷机", category: "Industrial machinery", price: 13200.00 },
  { num: 86, ar: "آلة أكياس أفقية مع مكدس", en: "Horizontal Bag Machine with Stacker", zh: "带堆垛机的水平制袋机", category: "Plastic Machinery", price: 14800.00 },
  { num: 87, ar: "آلة طباعة فلكسو (6 ألوان)", en: "Flexographic Printer (6 Colors)", zh: "柔版印刷机 (6色)", category: "Industrial machinery", price: 22000.00 },
  { num: 88, ar: "خط إنتاج أعواد البخور", en: "Incense Stick Production Line", zh: "香棒生产线", category: "Industrial machinery", price: 8600.00 },
  { num: 89, ar: "آلة نسيج دائرية (هيكلية)", en: "Circular Loom (Structural)", zh: "圆织机 (结构型)", category: "Textile Machinery", price: 13500.00 },
  { num: 90, ar: "آلة طباعة فلكسو (8 ألوان)", en: "Flexographic Printer (8 Colors)", zh: "柔版印刷机 (8色)", category: "Industrial machinery", price: 29000.00 },
  { num: 91, ar: "جرافة أمامية", en: "Wheel Loader", zh: "轮式装载机", category: "Loader", price: 34000.00 },
  { num: 92, ar: "جرافة بملحق خلط", en: "Loader with Mixing Attachment", zh: "带搅拌附件的装载机", category: "Loader", price: 38000.00 },
  { num: 93, ar: "جرافة برأس طحن", en: "Loader with Milling Head", zh: "带铣头的装载机", category: "Loader", price: 41000.00 },
  { num: 94, ar: "لفة سلك مجلفن", en: "Galvanized Wire Coil", zh: "镀锌钢丝卷", category: "Metal products", price: 620.00 },
  { num: 95, ar: "سلك مجلفن معبأ", en: "Packaged Galvanized Wire", zh: "包装好的镀锌钢丝", category: "Metal products", price: 680.00 },
  { num: 96, ar: "جرافة مائية", en: "Cutter Suction Dredger", zh: "绞吸式挖泥船", category: "Earth moving", price: 85000.00 },
  { num: 97, ar: "مجفف أسطواني دوار", en: "Rotary Drum Dryer", zh: "回转滚筒干燥机", category: "Industrial machinery", price: 16800.00 },
  { num: 98, ar: "ناقل حلزوني أفقي", en: "Horizontal Screw Conveyor", zh: "水平螺旋输送机", category: "Conveyors & Logistics", price: 3200.00 },
  { num: 99, ar: "آلة غسيل حوضية", en: "Washing Tank Machine", zh: "槽式清洗机", category: "Industrial machinery", price: 4500.00 },
  { num: 100, ar: "حزام ناقل صناعي", en: "Industrial Conveyor Belt", zh: "工业传送带", category: "Conveyors & Logistics", price: 2100.00 },
  { num: 101, ar: "آلة فرز مثبتة", en: "Overhead Sorting Machine", zh: "悬挂式分选机", category: "Conveyors & Logistics", price: 9800.00 },
  { num: 102, ar: "آلة غربلة اهتزازية", en: "Vibrating Screen Machine", zh: "振动筛分机", category: "Mining Equipment", price: 5400.00 },
  { num: 103, ar: "خزان صناعي مغلق", en: "Industrial Closed Tank", zh: "工业密闭罐", category: "Industrial machinery", price: 7200.00 },
  { num: 104, ar: "مغذي اهتزازي", en: "Vibrating Feeder", zh: "振动给料机", category: "Mining Equipment", price: 3800.00 },
  { num: 105, ar: "خلاطة حلزونية مزدوجة", en: "Twin-Shaft Mixer", zh: "双轴搅拌机", category: "Industrial machinery", price: 11500.00 },
  { num: 106, ar: "كسارة أسطوانية", en: "Roller Crusher", zh: "对辊破碎机", category: "Mining Equipment", price: 8900.00 },
  { num: 107, ar: "آلة غربلة دوارة", en: "Rotary Trommel Screen", zh: "滚筒筛分机", category: "Mining Equipment", price: 7600.00 },
  { num: 108, ar: "فاصل مغناطيسي أسطواني", en: "Magnetic Drum Separator", zh: "磁选滚筒", category: "Mining Equipment", price: 6200.00 },
  { num: 109, ar: "خزان معالجة مياه", en: "Water Treatment Tank", zh: "水处理池", category: "Industrial machinery", price: 12800.00 },
  { num: 110, ar: "وحدة محرك مع علبة تروس", en: "Geared Motor Unit", zh: "减速电机单元", category: "Heavy Machinery Parts", price: 1850.00 },
  { num: 111, ar: "آلة حصاد مائية", en: "Aquatic Harvester", zh: "水上收割机", category: "Harvesting tools", price: 22500.00 },
  { num: 112, ar: "خلاطة دفعة صناعية", en: "Industrial Batch Mixer", zh: "工业间歇式混合机", category: "Industrial machinery", price: 9400.00 },
  { num: 113, ar: "وحدة ضخ هيدروليكية", en: "Hydraulic Pump Unit", zh: "液压泵组", category: "Heavy Machinery Parts", price: 2750.00 },
  { num: 114, ar: "قادوس تغذية مزدوج", en: "Twin-Hopper Feeder", zh: "双料斗给料机", category: "Conveyors & Logistics", price: 4100.00 },
  { num: 115, ar: "مطحنة كروية أو مجفف", en: "Ball Mill / Dryer", zh: "球磨机/干燥机", category: "Mining Equipment", price: 19800.00 },
  { num: 116, ar: "فلتر زيت", en: "Oil Filter", zh: "机油滤清器", category: "Car spare parts", price: 18.00 },
  { num: 117, ar: "فلتر زيت MAHLE", en: "MAHLE Oil Filter", zh: "MAHLE机油滤清器", category: "Car spare parts", price: 28.00 },
  { num: 118, ar: "فلاتر زيت BOSCH", en: "BOSCH Oil Filters", zh: "BOSCH机油滤清器", category: "Car spare parts", price: 32.00 },
  { num: 119, ar: "فلاتر زيت مغلقة", en: "Spin-on Oil Filters", zh: "旋装式机油滤清器", category: "Car spare parts", price: 22.00 },
  { num: 120, ar: "فلتر وقود Donaldson", en: "Donaldson Fuel Filter", zh: "Donaldson燃油滤清器", category: "Car spare parts", price: 45.00 },
  { num: 121, ar: "شفرات قطع ماسية", en: "Diamond Saw Blades", zh: "金刚石锯片", category: "Laser & Cutting", price: 120.00 },
  { num: 122, ar: "شفرة فتح الأخاديد", en: "Slotting Saw Blade", zh: "开槽锯片", category: "Parts", price: 85.00 },
  { num: 123, ar: "شفرات ماسية مُثخنة", en: "Thickened Diamond Blades", zh: "加厚金刚石锯片", category: "Parts", price: 140.00 },
  { num: 124, ar: "صورة مقربة لشفرة الماس", en: "Close-up of Diamond Blade", zh: "金刚石锯片特写", category: "Parts", price: 95.00 },
  { num: 125, ar: "تطبيق شفرة الماس في النقش", en: "Diamond Blade in Sculpting", zh: "金刚石锯片在雕刻中的应用", category: "Parts", price: 160.00 },
  { num: 126, ar: "إبر بيطرية", en: "Veterinary Needles", zh: "兽用针头", category: "Agricultural machinery", price: 15.00 },
  { num: 127, ar: "طرق تركيب شفرة الماس", en: "Diamond Blade Installation Methods", zh: "金刚石锯片安装方法", category: "Parts", price: 75.00 },
  { num: 128, ar: "لفائف قطن طبي", en: "Medical Cotton Rolls", zh: "医用棉卷", category: "Products", price: 35.00 },
  { num: 129, ar: "آلة نفخ زجاجات (4 محطات)", en: "Bottle Blower (4 Stations)", zh: "吹瓶机 (4工位)", category: "Plastic Machinery", price: 16500.00 },
  { num: 130, ar: "آلة نفخ زجاجات (محطتان)", en: "Bottle Blower (2 Stations)", zh: "吹瓶机 (2工位)", category: "Plastic Machinery", price: 11200.00 },
  { num: 131, ar: "آلة نفخ مباشر (BT280)", en: "Direct Blowing Machine (BT280)", zh: "直吹式吹瓶机 (BT280)", category: "Plastic Machinery", price: 14800.00 },
  { num: 132, ar: "آلة نفخ زجاجات مزدوجة (BT80)", en: "Double-Station Blower (BT80)", zh: "双工位吹瓶机 (BT80)", category: "Plastic Machinery", price: 12900.00 },
  { num: 133, ar: "آلة نفخ مغلقة (BT120)", en: "Enclosed Blower (BT120)", zh: "封闭式吹瓶机 (BT120)", category: "Plastic Machinery", price: 15400.00 },
  { num: 134, ar: "آلة نفخ بلاستيك عمودية", en: "Vertical Plastic Blower", zh: "立式吹塑机", category: "Plastic Machinery", price: 13600.00 },
  { num: 135, ar: "آلة نفخ مباشر (BT200)", en: "Direct Blowing Machine (BT200)", zh: "直吹式吹瓶机 (BT200)", category: "Plastic Machinery", price: 14200.00 },
  { num: 136, ar: "مركبة نقل ثلاثية العجلات", en: "Cargo Tricycle", zh: "三轮货运车", category: "Three wheeled", price: 2800.00 },
  { num: 137, ar: "مركبة نقل ثلاثية العجلات (أزرق)", en: "Cargo Tricycle (Blue)", zh: "三轮货运车 (蓝色)", category: "Three wheeled", price: 2950.00 }
];

// Read ALL_UPLOADED_IMAGES list from mockData or dynamically
const mockDataPath = path.join(__dirname, '..', 'src', 'mockData.ts');
let mockContent = fs.readFileSync(mockDataPath, 'utf-8');

// Build product objects
const products = itemsData.map((item, idx) => {
  const short_en = item.en + " - Industrial grade equipment from Sdazum Global.";
  const short_ar = item.short_ar || (item.ar + " - معدات صناعية عالية الجودة من سدازوم غلوبال.");
  const short_zh = item.zh + " - 威海/山东SD Azum 工业级设备。";

  const desc_en = item.desc_ar ? (item.en + ". " + item.desc_ar) : `${item.en} (${item.zh} / ${item.ar}) is manufactured with high precision materials by Shandong Azum Import & Export Co., Ltd. Suitable for professional industrial operation.`;
  const desc_ar = item.desc_ar || `${item.ar} (${item.en} - ${item.zh}) المصنعة بأعلى معايير الجودة من شركة شاندونغ أزوم للاستيراد والتصدير. مناسبة للاستخدام الصناعي والمهني.`;
  const desc_zh = `${item.zh} (${item.en} / ${item.ar}) 由山东阿祖姆进出口有限公司采用高精度材料制造。适用于专业工业操作。`;

  return {
    id: `prod-sdazum-${String(item.num).padStart(3, '0')}`,
    name: item.en,
    name_en: item.en,
    name_zh: item.zh,
    name_ar: item.ar,
    shortDescription: short_en,
    short_en: short_en,
    short_zh: short_zh,
    short_ar: short_ar,
    description: desc_en,
    desc_en: desc_en,
    desc_zh: desc_zh,
    desc_ar: desc_ar,
    price: item.price,
    category: item.category,
    sizes: ['Standard', 'Heavy Duty'],
    colors: [
      { name: 'Industrial Grey', value: '#475569' },
      { name: 'Machine Blue', value: '#1E3A8A' }
    ],
    image: `img_${item.num}`, // Placeholder to be replaced with real image imports in TS
    rating: Number((4.5 + (idx % 5) * 0.1).toFixed(1)),
    salesCount: 15 + (idx * 7) % 180,
    stock: 10 + (idx * 3) % 40
  };
});

fs.writeFileSync(path.join(__dirname, 'products_gen.json'), JSON.stringify(products, null, 2));
console.log('Generated products count:', products.length);
